---
# dotfile role vars
os: macos
gitconfig_name: "Kartik Vashistha"
gitconfig_email: "kartikv.work@gmail.com"
wsl: false

# List of non gui pkgs to be installed via homebrew
brew_pkgs:
  - ansible
  - asdf
  - autoconf
  - automake
  - ca-certificates
  - coreutils
  - cryptography
  - fastfetch
  - fzf
  - git
  - gnupg
  - gnutls
  - go
  - helm
  - htop
  - kubernetes-cli
  - lazydocker
  - lazygit
  - luajit
  - minikube
  - molecule
  - ncurses
  - neofetch
  - neovim
  - node
  - openldap
  - pyenv
  - pyenv-virtualenv
  - pyenv-virtualenvwrapper
  - python@3.11
  - python@3.12
  - python@3.8
  - ranger
  - readline
  - ripgrep
  - sqlite
  - starship
  - tmux
  - tree-sitter
  - virtualenv
  - virtualenvwrapper

# List of gui apps to be installed via homebrew casks
brew_casks:
  - 1password
  - discord
  - docker
  - dropbox
  - firefox
  - font-fira-mono-nerd-font
  - font-hack-nerd-font
  - font-input
  - font-jetbrains-mono-nerd-font
  - google-chrome
  - google-cloud-sdk
  - iterm2
  - jellyfin
  - jetbrains-toolbox
  - kitty
  - qbittorrent
  - rectangle
  - scroll-reverser
  - signal
  - spotify
  - visual-studio-code
  - vlc
  - wezterm
  - kitty
