---
neovim_home_user_path: "{{ ansible_facts['env']['HOME'] }}" # Home Path of the user where you want to install the dotfiles

neovim_install_nvim_distros: false # Boolean flag to install multiple neovim distros

neovim_shell_file_path: "{{ neovim_home_user_path }}/.zshrc" # Full path of the shell rc file or equivalent

neovim_nvim_distros_list: # List of neovim distros you want to install & access via $NVIM_APPNAME
  - repo: https://github.com/AstroNvim/template
    dist_name: AstroNvim
    alias: nvim-astro
  - repo: https://github.com/nvim-lua/kickstart.nvim
    dist_name: kickstart
    alias: nvim-kick
  - repo: https://github.com/LazyVim/starter
    dist_name: LazyVim
    alias: nvim-lazy
  - repo: https://github.com/NvChad/starter
    dist_name: NvChad
    alias: nvim-chad
