---
# handlers file for setup-fedora
- name: Start Docker Service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Reboot system
  ansible.builtin.reboot:
  become: true
