# vim:ft=yaml.ansible
- name: Run the setup-fedora role
  hosts: localhost
  become: true

  vars_files:
    - group_vars/wsl-dotfiles-vars.yml
    - group_vars/wsl-fedora-vars.yml

  roles:
    - role: setup-fedora
    - role: dotfiles
