---
# vim:ft=yaml.ansible
# Handy little playbook that displays all data that are accessible to Ansible. Useful for debugging and discovery.
- name: Display system facts that are available to Ansible
  hosts: localhost
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: Print env
      ansible.builtin.debug:
        var: ansible_facts['env']
    - name: Print distribution
      ansible.builtin.debug:
        var: ansible_facts['distribution']
