---
# Tasks file for setup-fedora
- name: Install zsh
  ansible.builtin.dnf:
    name: zsh
    state: present
  become: true
  become_user: root

- name: Change shell to zsh
  ansible.builtin.user:
    name: "{{ fedora_home_username }}"
    shell: /bin/zsh
  become: true
  become_user: root

- name: Enable rpm fusion free & non free repos
  ansible.builtin.dnf:
    name: "{{ fedora_rpmfusion_free }}, {{ fedora_rpmfusion_non_free }}"
    state: present
    disable_gpg_check: true
  become: true
  become_user: root

- name: Add third party repos
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    baseurl: "{{ item.baseurl | default(omit) }}"
    enabled: "{{ item.enabled | default(omit) }}"
    gpgcheck: "{{ item.gpgcheck | default(omit) }}"
    repo_gpgcheck: "{{ item.repo_gpgcheck | default(omit) }}"
    gpgkey: "{{ item.gpgkey | default(omit) }}"
    skip_if_unavailable: "{{ item.skip_if_unavailable | default(omit) }}"
    metadata_expire: "{{ item.metadata_expire | default(omit) }}"
  with_items: "{{ fedora_third_party_repos }}"
  when: fedora_third_party_repos | length > 0
  become: true
  become_user: root

- name: Install Copr repos
  community.general.copr:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ fedora_copr_repos }}"
  when: fedora_copr_repos | length > 0
  become_user: root
  become: true

- name: Install groups
  ansible.builtin.dnf:
    name: "{{ fedora_grouplist }}"
    state: present
  become: true
  become_user: root

- name: Install a list of packages
  ansible.builtin.dnf:
    name: "{{ fedora_packages }}"
    state: present
    disable_gpg_check: true
  become_user: root
  become: true

- name: Install nvidia packages from rpmfusion
  ansible.builtin.include_tasks: nvidia.yml
  when: fedora_nvidia

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: "{{ fedora_flatpak_repo }}"
    method: system
  when: fedora_enable_flatpak

- name: Install flatpak applications
  community.general.flatpak:
    name: "{{ item }}"
    remote: flathub
    state: present
  with_items: "{{ fedora_flatpak }}"
  when: fedora_enable_flatpak

# Install & configure Docker
- name: Docker install and configuration
  ansible.builtin.include_tasks: docker.yml
  when: fedora_docker

- name: Install commitizen-cli node.js package globally
  community.general.npm:
    name: commitizen
    global: true
  become: true

- name: Install cz-conventional-changelog node.js package globally
  community.general.npm:
    name: cz-conventional-changelog
    global: true
  become: true
