---
local:
  hosts:
    localhost:
      ansible_connection: local

fedora_workstation:
  hosts:
    novigrad.home.arpa:

novigrad:
  hosts:
    novigrad.home.arpa: # pc
      ansible_connection: local

snowpiercer:
  hosts:
    snowpiercer.home.arpa: # macbook
      ansible_connection: local

home_servers:
  hosts:
    oxenfurt.home.arpa:
      ansible_connection: ssh
      ansible_user: "{{ lookup('community.general.onepassword', 'oxenfurt.home.arpa', field='username', vault='Private') }}"
      ansible_port: 22
      ansible_password: "{{ lookup('community.general.onepassword', 'oxenfurt.home.arpa', field='password', vault='Private') }}"
      ansible_become_password: "{{ lookup('community.general.onepassword', 'oxenfurt.home.arpa', field='password', vault='Private') }}"

    velen.home.arpa:
      ansible_connection: ssh
      ansible_user: "{{ lookup('community.general.onepassword', 'velen.home.arpa', field='username', vault='Private') }}"
      ansible_port: 22
      ansible_password: "{{ lookup('community.general.onepassword', 'velen.home.arpa', field='password', vault='Private') }}"
      ansible_become_password: "{{ lookup('community.general.onepassword', 'velen.home.arpa', field='password', vault='Private') }}"
