---
local:
  hosts:
    localhost:
      ansible_connection: local
    novigrad.home.arpa: # pc
      ansible_connection: local
    vanaheim.home.arpa: # macbook
      ansible_connection: local

oxenfurt:
  hosts:
    oxenfurt.home.arpa:
      ansible_connection: ssh
      ansible_user: "{{ vault_oxenfurt_ansible_user }}"
      ansible_port: 22
      ansible_password: "{{ vault_oxenfurt_ansible_password }}"
      ansible_become_password: "{{ vault_oxenfurt_ansible_become_password }}"

velen:
  hosts:
    velen.home.arpa:
      ansible_connection: ssh
      ansible_user: "{{ vault_velen_ansible_user }}"
      ansible_port: 22
      ansible_password: "{{ vault_velen_ansible_password }}"
      ansible_become_password: "{{ vault_velen_ansible_become_password }}"

kubernetes_master_nodes:
  children:
    velen:

kubernetes_worker_nodes:
  children:
    oxenfurt:

kubernetes:
  children:
    kubernetes_master_nodes:
    kubernetes_worker_nodes:
