---
local:
  hosts:
    localhost:
      ansible_connection: local

personal_workstation:
  hosts:
    novigrad.home.arpa: # pc
      ansible_connection: local
    vanaheim.home.arpa: # macbook
      ansible_connection: local

kubernetes_master_nodes:
  hosts:
    velen.home.arpa:
      ansible_connection: ssh
      ansible_user: "{{ vault_velen_ansible_user }}"
      ansible_port: 22
      ansible_password: "{{ vault_velen_ansible_password }}"
      ansible_become_password: "{{ vault_velen_ansible_become_password }}"

kubernetes_worker_nodes:
  hosts:
    oxenfurt.home.arpa:
      ansible_connection: ssh
      ansible_user: "{{ vault_oxenfurt_ansible_user }}"
      ansible_port: 22
      ansible_password: "{{ vault_oxenfurt_ansible_password }}"
      ansible_become_password: "{{ vault_oxenfurt_ansible_become_password }}"

kubernetes:
  children:
    kubernetes_master_nodes:
    kubernetes_worker_nodes:
