---
local:
  hosts:
    localhost:
      ansible_connection: local

fedora_local:
  hosts:
    novigrad.home.arpa:
      ansible_connection: local

macos_local:
  hosts:
    snowpiercer.home.arpa:
      ansible_connection: local

kubernetes:
  hosts:
    velen.home.arpa:
      ansible_connection: ssh
      ansible_user: kartik
      ansible_port: 22
      ansible_password: ""
      ansible_become_password: ""

