---
# Tasks file for setup-fedora
- name: Install zsh
  ansible.builtin.dnf:
    name: zsh
    state: present
  become: true
  become_user: root

- name: Change shell to zsh
  ansible.builtin.user:
    name: "{{ home_username }}"
    shell: /bin/zsh
  become: true
  become_user: root

- name: Enable rpm fusion free & non free repos
  ansible.builtin.dnf:
    name: "{{ rpmfusion_free }}, {{ rpmfusion_non_free }}"
    state: present
    disable_gpg_check: true
  become: true
  become_user: root

- name: Add third party repos
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    baseurl: "{{ item.baseurl | default(omit) }}"
    enabled: "{{ item.enabled | default(omit) }}"
    gpgcheck: "{{ item.gpgcheck | default(omit) }}"
    repo_gpgcheck: "{{ item.repo_gpgcheck | default(omit) }}"
    gpgkey: "{{ item.gpgkey | default(omit) }}"
    skip_if_unavailable: "{{ item.skip_if_unavailable | default(omit) }}"
    metadata_expire: "{{ item.metadata_expire | default(omit) }}"
  with_items: "{{ third_party_repos }}"
  become: true
  become_user: root

- name: Install Copr repos
  community.general.copr:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ copr_repos }}"
  become_user: root
  become: true

- name: Install groups
  ansible.builtin.dnf:
    name: "{{ grouplist }}"
    state: present
  become: true
  become_user: root

- name: Install a list of packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
    disable_gpg_check: true
  become_user: root
  become: true

- name: Install nvidia packages from rpmfusion
  ansible.builtin.include_tasks: nvidia.yml
  when: nvidia


- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
  when: enable_flatpak

- name: Install flatpak applications
  community.general.flatpak:
    name: "{{ item }}"
    remote: flathub
    state: present
  with_items: "{{ flatpak }}"
  when: enable_flatpak

- name: Clone Nerd Fonts repo
  ansible.builtin.git:  # noqa: latest
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: "{{ home_user_path }}/code/nerd-fonts"
    depth: 1
  when: clone_nerdfonts

# Install & configure Docker
- name: Docker install and configuration
  ansible.builtin.include_tasks: docker.yml
  when: docker

- name: Clone & install asdf
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ home_user_path }}/.asdf"
    version: v0.13.1

- name: Install commitizen node.js package globally
  community.general.npm:
    name: commitizen
    global: true

- name: Install conventional-changelog node.js package globally
  community.general.npm:
    name: commitizen
    global: true
