---
# defaults file for asdf
asdf_home_dir: "{{ ansible_facts['env']['HOME'] }}"
asdf_dir: "{{ asdf_home_dir }}/.asdf"
asdf_releases_dir: "{{ asdf_home_dir }}/.cache/asdf-releases"
asdf_tool_file_path: "{{ ansible_facts['env']['HOME'] }}"

asdf_release_tag: "v0.16.7"
asdf_release_platform: "linux"
asdf_release_arch: "amd64"
asdf_archive_file: "asdf-{{ asdf_release_tag }}-{{ asdf_release_platform }}-{{ asdf_release_arch }}.tar.gz"
asdf_release_url: "https://github.com/asdf-vm/asdf/releases/download/{{ asdf_release_tag }}/{{ asdf_archive_file }}"

asdf_checksum_algorithm: "md5"
asdf_release_checksum_url: "{{ asdf_releases_url }}/{{ asdf_release_tag }}/asdf-{{ asdf_release_tag }}-{{ asdf_release_platform }}-\
                          {{ asdf_release_arch }}.tar.gz.{{ asdf_checksum_algorithm }}"

asdf_binary_name: "asdf"
asdf_binary_path: "{{ asdf_home_dir }}/.local/bin"
asdf_file_to_append_path_in: "{{ asdf_home_dir }}/.zprofile"

asdf_install_via_homebrew: false
asdf_install_via_gh_releases: true

asdf_plugins:
  - name: "terraform"
    repo: "https://github.com/asdf-community/asdf-hashicorp.git"
    default_version: "1.8.3"
  - name: "java"
    repo: "https://github.com/halcyon/asdf-java.git"
    default_version: "temurin-21.0.2+13.0.LTS"
