---
# tasks file for setup-macos
- name: Update homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Install brew pkgs
  community.general.homebrew:
    name: "{{ brew_pkgs }}"
    state: present

- name: Install brew casks
  community.general.homebrew_cask:
    name: "{{ brew_casks }}"
    state: present

- name: Install commitizen node.js package globally
  community.general.npm:
    name: commitizen
    global: true

- name: Install cz-conventional-changelog node.js package globally
  community.general.npm:
    name: cz-conventional-changelog
    global: true
