---
# vim:ft=yaml.ansible
- name: Run the setup-fedora role
  hosts: "{{ host_group | default('local') }}"
  become: true

  vars:
  # dotfile role vars
    dotfiles_wsl: true
  # setup-fedora role vars
    nvidia: false
    docker: false
    clone_nerdfonts: false
    enable_flatpak: false

    packages:
      - bc
      - unzip
      - neofetch
      - fzf
      - golang
      - htop
      - glances
      - vim-enhanced
      - samba
      - neovim
      - python3-virtualenvwrapper
      - nodejs
      - gcc
      - gcc-c++
      - make
      - kubectl

    grouplist:
      - '@core'
      - '@virtualization'

    third_party_repos:
      - name: google-cloud-sdk.repo
        description: Google Cloud CLI
        baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64
        enabled: true
        gpgcheck: true
        repo_gpgcheck: false
        gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  roles:
    - role: setup-fedora
    - role: dotfiles
    - role: neovim
