# vim:ft=yaml.ansible
- name: Run the setup-fedora role
  hosts: "{{ host_group }}"
  become: true

  vars_files:
    - group_vars/fedora-wsl-vars.yml

  roles:
    - role: setup-fedora
    - role: dotfiles
    - role: neovim
