# Playbook to configure my Fedora Workstation machine
# vim:ft=yaml.ansible
- name: Setup a Fedora Workstation machine
  hosts: novigrad.home.arpa
  roles:
    - role: fedora
    - role: asdf
    - role: dotfiles
    - role: neovim
