---
# vim:ft=yaml.ansible
- name: Setup a Fedora Workstation machine
  hosts: "{{ host_group | default('local') }}"

  roles:
    - role: setup-fedora
    - role: asdf
    - role: dotfiles
    - role: neovim
