# vim:ft=yaml.ansible
- name: Setup a macOS machine
  hosts: "{{ host_group }}"

  vars_files:
    - group_vars/macos-vars.yml

  roles:
    - role: setup-macos
    - role: dotfiles
    - role: neovim
