# Playbook to configure my personal macbook machine
# vim:ft=yaml.ansible
- name: Setup a macOS machine
  hosts: snowpiercer.home.arpa
  roles:
    - role: macos
    - role: asdf
    - role: dotfiles
    - role: neovim
