---
# vim:ft=yaml.ansible
- name: Update all system packages
  hosts: "{{ host_group | default('local') }}"

  tasks:
    - name: Upgrade all packages on a Fedora system
      ansible.builtin.dnf:
        name: "*"
        state: latest # noqa package-latest
      when: ansible_facts['distribution'] == "Fedora"
      become: true
      become_user: root
